# Generated by Django 4.2.30 on 2026-05-18 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('export', 'Export Data'), ('register', 'User Registration'), ('failed_login', 'Failed Login Attempt'), ('password_reset', 'Password Reset'), ('permission_denied', 'Permission Denied')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, help_text='Model affected (e.g., Patient, CareNote)', max_length=50)),
                ('object_id', models.IntegerField(blank=True, help_text='ID of object affected', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx')],
            },
        ),
    ]
