# Generated by Django 4.2.30 on 2026-05-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, help_text='Model affected (e.g., Patient, CareNote)', max_length=50, null=True),
        ),
    ]
