# Generated by Django 6.0.2 on 2026-03-14 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='breaths/min', null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=4, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pain_score', models.IntegerField(blank=True, help_text='0-10 scale', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
