# Generated by Django 6.0.2 on 2026-03-14 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal_care', 'Personal Care'), ('nutrition', 'Nutrition & Hydration'), ('clinical', 'Clinical'), ('wellbeing', 'Emotional Wellbeing'), ('activity', 'Activity & Engagement'), ('sleep', 'Sleep'), ('continence', 'Continence'), ('social', 'Social Interaction')], max_length=30)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('important', 'Important'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
