# Generated by Django 4.2.30 on 2026-07-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_voicemedicationdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemedicationdraft',
            name='witnessed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
