# Generated by Django 6.0.2 on 2026-03-15 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('morning_wash', 'Morning Wash / Personal Care'), ('oral_care', 'Oral Care'), ('breakfast', 'Breakfast & Fluids'), ('morning_meds', 'Morning Medications'), ('pressure_care_am', 'Pressure Area Check (AM)'), ('obs_60_1', '60 Min Observation — 07:00'), ('obs_60_2', '60 Min Observation — 08:00'), ('obs_60_3', '60 Min Observation — 09:00'), ('obs_60_4', '60 Min Observation — 10:00'), ('obs_60_5', '60 Min Observation — 11:00'), ('lunch', 'Lunch & Fluids'), ('lunch_meds', 'Lunchtime Medications'), ('obs_60_6', '60 Min Observation — 12:00'), ('obs_60_7', '60 Min Observation — 13:00'), ('obs_60_8', '60 Min Observation — 14:00'), ('vitals_pm', 'Vital Signs Recording (PM)'), ('repositioning_pm', 'Repositioning / Turning (PM)'), ('obs_60_9', '60 Min Observation — 15:00'), ('obs_60_10', '60 Min Observation — 16:00'), ('afternoon_tea', 'Afternoon Tea & Snack'), ('activity', 'Activity / Engagement'), ('dinner', 'Dinner & Fluids'), ('evening_meds', 'Evening Medications'), ('obs_60_11', '60 Min Observation — 17:00'), ('obs_60_12', '60 Min Observation — 18:00'), ('obs_60_13', '60 Min Observation — 19:00'), ('evening_wash', 'Evening Wash / Freshen Up'), ('oral_care_pm', 'Evening Oral Care'), ('pressure_care_pm', 'Pressure Area Check (PM)'), ('night_meds', 'Night Medications'), ('obs_60_14', '60 Min Observation — 20:00'), ('obs_60_15', '60 Min Observation — 21:00'), ('obs_60_16', '60 Min Observation — 22:00'), ('obs_60_17', '60 Min Observation — 23:00'), ('obs_60_18', '60 Min Observation — 00:00'), ('obs_60_19', '60 Min Observation — 01:00'), ('obs_60_20', '60 Min Observation — 02:00'), ('obs_60_21', '60 Min Observation — 03:00'), ('obs_60_22', '60 Min Observation — 04:00'), ('obs_60_23', '60 Min Observation — 05:00'), ('obs_60_24', '60 Min Observation — 06:00'), ('repositioning_night', 'Repositioning / Turning (Night)'), ('vitals_am', 'Vital Signs Recording (AM)')], max_length=30)),
                ('shift', models.CharField(choices=[('morning', 'Morning (07:00–13:00)'), ('afternoon', 'Afternoon (13:00–19:00)'), ('night', 'Night (19:00–07:00)')], max_length=10)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='patients.patient')),
            ],
            options={
                'ordering': ['due_date', 'task_type'],
                'unique_together': {('patient', 'task_type', 'due_date')},
            },
        ),
    ]
