# Generated by Django 6.0.2 on 2026-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caretask',
            options={'ordering': ['due_date', 'due_time', 'task_type']},
        ),
        migrations.AddField(
            model_name='caretask',
            name='due_time',
            field=models.CharField(blank=True, help_text='HH:MM', max_length=5),
        ),
        migrations.AddField(
            model_name='caretask',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='caretask',
            name='task_type',
            field=models.CharField(choices=[('obs_60_07', '60 Min Observation — 07:00'), ('obs_60_08', '60 Min Observation — 08:00'), ('obs_60_09', '60 Min Observation — 09:00'), ('obs_60_10', '60 Min Observation — 10:00'), ('obs_60_11', '60 Min Observation — 11:00'), ('obs_60_12', '60 Min Observation — 12:00'), ('obs_60_13', '60 Min Observation — 13:00'), ('obs_60_14', '60 Min Observation — 14:00'), ('obs_60_15', '60 Min Observation — 15:00'), ('obs_60_16', '60 Min Observation — 16:00'), ('obs_60_17', '60 Min Observation — 17:00'), ('obs_60_18', '60 Min Observation — 18:00'), ('obs_60_19', '60 Min Observation — 19:00'), ('obs_60_20', '60 Min Observation — 20:00'), ('obs_60_21', '60 Min Observation — 21:00'), ('obs_60_22', '60 Min Observation — 22:00'), ('obs_60_23', '60 Min Observation — 23:00'), ('obs_60_00', '60 Min Observation — 00:00'), ('obs_60_01', '60 Min Observation — 01:00'), ('obs_60_02', '60 Min Observation — 02:00'), ('obs_60_03', '60 Min Observation — 03:00'), ('obs_60_04', '60 Min Observation — 04:00'), ('obs_60_05', '60 Min Observation — 05:00'), ('obs_60_06', '60 Min Observation — 06:00'), ('temperature_check', 'Temperature Check'), ('blood_pressure_check', 'Blood Pressure Check'), ('pulse_check', 'Pulse / Heart Rate Check'), ('oxygen_saturation_check', 'Oxygen Saturation (SpO2) Check'), ('respiration_rate_check', 'Respiratory Rate Check'), ('pain_assessment', 'Pain Assessment'), ('morning_wash', 'Morning Wash'), ('bed_bath', 'Full Bed Bath'), ('shower_assistance', 'Shower Assistance'), ('oral_care', 'Oral Care (Morning)'), ('oral_care_pm', 'Oral Care (Evening)'), ('hair_care', 'Hair Care / Grooming'), ('shaving_assistance', 'Shaving Assistance'), ('nail_care', 'Nail Care'), ('dressing_assistance', 'Dressing Assistance'), ('evening_wash', 'Evening Wash / Freshen Up'), ('continence_pad_change', 'Continence Pad Change'), ('toileting_assistance', 'Toileting Assistance'), ('perineal_care', 'Perineal Care'), ('morning_meds', 'Morning Medications'), ('lunch_meds', 'Lunchtime Medications'), ('evening_meds', 'Evening Medications'), ('night_meds', 'Night Medications'), ('prn_medication', 'PRN Medication (As Required)'), ('medication_round_check', 'Medication Round Check'), ('medication_refusal_record', 'Medication Refusal Record'), ('controlled_drug_check', 'Controlled Drug Check'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('afternoon_tea', 'Afternoon Tea & Snack'), ('assist_feeding', 'Feeding Assistance'), ('record_food_intake', 'Food Intake Record'), ('monitor_swallowing', 'Swallowing / Dysphagia Monitoring'), ('hydration_check', 'Hydration Check'), ('fluid_intake_record', 'Fluid Intake Record'), ('encourage_fluids', 'Encourage Fluids'), ('nutritional_supplement', 'Nutritional Supplement'), ('special_diet_check', 'Special Diet Check'), ('mobility_assistance', 'Mobility Assistance'), ('walking_support', 'Walking Support'), ('wheelchair_transfer', 'Wheelchair Transfer'), ('bed_to_chair_transfer', 'Bed to Chair Transfer'), ('physiotherapy_exercises', 'Physiotherapy Exercises'), ('mobility_assessment', 'Mobility Assessment'), ('fall_risk_monitoring', 'Fall Risk Monitoring'), ('repositioning_pm', 'Repositioning / Turning (PM)'), ('repositioning_night', 'Repositioning / Turning (Night)'), ('pressure_care_am', 'Pressure Area Care (AM)'), ('pressure_care_pm', 'Pressure Area Care (PM)'), ('skin_integrity_check', 'Skin Integrity Check'), ('pressure_area_check', 'Pressure Area Check'), ('apply_barrier_cream', 'Apply Barrier / Moisturising Cream'), ('inspect_wounds', 'Inspect Wounds'), ('dressing_change', 'Dressing Change'), ('wound_care', 'Wound Care'), ('pressure_ulcer_monitoring', 'Pressure Ulcer Monitoring'), ('wellbeing_check', 'Wellbeing Check'), ('mood_observation', 'Mood Observation'), ('cognitive_stimulation', 'Cognitive Stimulation'), ('engage_social_activity', 'Social Activity / Engagement'), ('music_therapy', 'Music Therapy'), ('reading_activity', 'Reading / Story Time'), ('group_activity', 'Group Activity'), ('one_to_one_conversation', 'One-to-One Conversation'), ('sleep_check', 'Sleep Check'), ('night_round_check', 'Night Round Check'), ('restlessness_monitoring', 'Restlessness Monitoring'), ('sleep_pattern_record', 'Sleep Pattern Record'), ('comfort_check', 'Comfort Check'), ('bed_position_check', 'Bed Position Check'), ('infection_symptom_check', 'Infection Symptom Check'), ('temperature_monitoring', 'Temperature Monitoring'), ('ppe_compliance_check', 'PPE Compliance Check'), ('hand_hygiene_check', 'Hand Hygiene Check'), ('isolation_precaution_check', 'Isolation Precaution Check'), ('room_cleanliness_check', 'Room Cleanliness Check'), ('bed_rails_check', 'Bed Rails Check'), ('call_bell_check', 'Call Bell Check'), ('room_safety_check', 'Room Safety Check'), ('trip_hazard_check', 'Trip Hazard Check'), ('lighting_check', 'Lighting Check'), ('fire_exit_check', 'Fire Exit Check'), ('emergency_equipment_check', 'Emergency Equipment Check'), ('family_update_call', 'Family Update Call'), ('visitor_log', 'Visitor Log'), ('family_concern_followup', 'Family Concern Follow-up'), ('care_plan_review', 'Care Plan Review'), ('handover_note', 'Shift Handover Note'), ('incident_report', 'Incident Report')], max_length=40),
        ),
    ]
