# Generated by Django 6.0.2 on 2026-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('care_assistant', 'Care Assistant'), ('family', 'Family Member')], default='care_assistant', max_length=20),
        ),
    ]
