# Generated by Django 4.2.30 on 2026-05-18 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_widgets', models.JSONField(default=list, help_text='List of visible widget names in order')),
                ('widget_order', models.JSONField(default=dict, help_text='Widget display order')),
                ('dark_mode', models.BooleanField(default=False)),
                ('show_notifications', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=30, help_text='Auto-refresh interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Preferences',
            },
        ),
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('warning', 'Warning'), ('info', 'Information'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bi-bell', max_length=50)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_d_user_id_0c0389_idx'), models.Index(fields=['user', 'is_read'], name='dashboard_d_user_id_561e39_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('patient_created', 'Patient Created'), ('patient_updated', 'Patient Updated'), ('care_note_added', 'Care Note Added'), ('medication_administered', 'Medication Administered'), ('vitals_recorded', 'Vitals Recorded'), ('user_login', 'User Login'), ('report_generated', 'Report Generated'), ('handover_completed', 'Handover Completed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dashboard_d_created_3ad65b_idx'), models.Index(fields=['user', '-created_at'], name='dashboard_d_user_id_b651a6_idx')],
            },
        ),
    ]
