# Generated by Django 4.2.30 on 2026-05-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift (7am - 7pm)'), ('night', 'Night Shift (7pm - 7am)'), ('custom', 'Custom Hours')], default='day', max_length=20)),
                ('start_time', models.TimeField(default='07:00', help_text='Shift start time (HH:MM)')),
                ('end_time', models.TimeField(default='19:00', help_text='Shift end time (HH:MM)')),
                ('shift_date', models.DateField(auto_now=True, help_text='Date of the shift')),
                ('is_active', models.BooleanField(default=True, help_text='Is this shift currently active?')),
                ('notes', models.TextField(blank=True, help_text='Any notes about the shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_shift', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Shifts',
                'ordering': ['-shift_date'],
                'indexes': [models.Index(fields=['user', '-shift_date'], name='dashboard_u_user_id_c59aa9_idx'), models.Index(fields=['user', 'is_active'], name='dashboard_u_user_id_06e655_idx')],
                'unique_together': {('user', 'shift_date')},
            },
        ),
    ]
