# Generated by Django 6.0.2 on 2026-03-15 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carenote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='carenote',
            name='appetite',
            field=models.CharField(blank=True, choices=[('all', 'All eaten'), ('most', 'Most eaten (75%+)'), ('half', 'About half eaten (50%)'), ('little', 'Little eaten (25%)'), ('none', 'Nothing eaten'), ('declined', 'Meal declined'), ('fed', 'Required feeding assistance'), ('peg', 'PEG / enteral feed')], max_length=10),
        ),
        migrations.AddField(
            model_name='carenote',
            name='continence',
            field=models.CharField(blank=True, choices=[('continent', 'Continent'), ('pad_changed', 'Pad / incontinence aid changed'), ('catheter_emptied', 'Catheter bag emptied'), ('toileted', 'Assisted to toilet'), ('incontinent_urine', 'Incontinent of urine'), ('incontinent_faeces', 'Incontinent of faeces'), ('incontinent_both', 'Incontinent of urine and faeces'), ('constipated', 'Reported constipation'), ('diarrhoea', 'Diarrhoea noted')], max_length=25),
        ),
        migrations.AddField(
            model_name='carenote',
            name='falls_risk_observed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carenote',
            name='fluid_amount_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carenote',
            name='fluid_intake',
            field=models.CharField(blank=True, choices=[('good', 'Good (1500ml+)'), ('adequate', 'Adequate (1000–1499ml)'), ('poor', 'Poor (<1000ml)'), ('declined', 'Fluids declined'), ('thickened', 'Thickened fluids only'), ('iv_fluids', 'IV fluids in progress')], max_length=10),
        ),
        migrations.AddField(
            model_name='carenote',
            name='meal_time',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('mid_morning_snack', 'Mid-morning snack'), ('lunch', 'Lunch'), ('afternoon_tea', 'Afternoon tea'), ('dinner', 'Dinner'), ('evening_snack', 'Evening snack'), ('supplement', 'Nutritional supplement')], max_length=25),
        ),
        migrations.AddField(
            model_name='carenote',
            name='mobility_aid',
            field=models.CharField(blank=True, choices=[('independent', 'Independent — no aid'), ('walking_stick', 'Walking stick'), ('zimmer_frame', 'Zimmer frame / walking frame'), ('rollator', 'Rollator / wheeled walker'), ('wheelchair', 'Wheelchair'), ('hoist', 'Hoist required'), ('two_staff', 'Two staff assist'), ('one_staff', 'One staff assist'), ('bed_bound', 'Bed-bound')], max_length=20),
        ),
        migrations.AddField(
            model_name='carenote',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy / content'), ('settled', 'Calm and settled'), ('anxious', 'Anxious / worried'), ('low', 'Low mood / tearful'), ('agitated', 'Agitated / restless'), ('aggressive', 'Verbally aggressive'), ('physically_aggressive', 'Physically aggressive'), ('confused', 'Confused / disoriented'), ('withdrawn', 'Withdrawn / uncommunicative'), ('fatigued', 'Tired / fatigued')], max_length=30),
        ),
        migrations.AddField(
            model_name='carenote',
            name='obs_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carenote',
            name='obs_location',
            field=models.CharField(blank=True, choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom / Toilet'), ('lounge', 'Lounge / Sitting Room'), ('dining_room', 'Dining Room'), ('corridor', 'Corridor'), ('garden', 'Garden / Outdoor Area'), ('activity_room', 'Activity Room'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='carenote',
            name='obs_status',
            field=models.CharField(blank=True, choices=[('sleeping', 'Appears to be sleeping'), ('awake_settled', 'Awake and settled'), ('awake_active', 'Awake and active'), ('awake_distressed', 'Awake and distressed'), ('awake_confused', 'Awake and confused'), ('engaged', 'Engaged in activity'), ('eating', 'Eating / drinking'), ('personal_care', 'Receiving personal care'), ('other', 'Other — see notes')], max_length=30),
        ),
        migrations.AddField(
            model_name='carenote',
            name='oral_care',
            field=models.CharField(blank=True, choices=[('teeth_brushed', 'Teeth brushed'), ('dentures_cleaned', 'Dentures cleaned'), ('mouthwash', 'Mouthwash used'), ('declined', 'Resident declined')], max_length=20),
        ),
        migrations.AddField(
            model_name='carenote',
            name='pressure_area',
            field=models.CharField(blank=True, choices=[('intact', 'Skin intact — no concerns'), ('redness', 'Redness / discolouration noted'), ('blister', 'Blister noted'), ('wound_present', 'Wound present — see wound care note'), ('heels_offloaded', 'Heels offloaded'), ('cream_applied', 'Barrier / moisturising cream applied')], max_length=20),
        ),
        migrations.AddField(
            model_name='carenote',
            name='repositioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carenote',
            name='repositioned_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carenote',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='carenote',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('good', 'Good — slept through'), ('fair', 'Fair — some waking'), ('poor', 'Poor — frequently awake'), ('none', 'Did not sleep'), ('nap', 'Short nap only')], max_length=10),
        ),
        migrations.AddField(
            model_name='carenote',
            name='wash_type',
            field=models.CharField(blank=True, choices=[('full_bed_bath', 'Full bed bath'), ('assisted_shower', 'Assisted shower'), ('assisted_bath', 'Assisted bath'), ('stand_wash', 'Stand-up wash'), ('face_hands', 'Face and hands only'), ('declined', 'Resident declined')], max_length=20),
        ),
        migrations.AddField(
            model_name='carenote',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='carenote',
            name='category',
            field=models.CharField(choices=[('observation_60', '60 Min (Hourly) Observation'), ('observation_30', '30 Min Observation'), ('observation_15', '15 Min Observation'), ('observation_eod', 'End of Shift / Timeline Review'), ('personal_care', 'Personal Care'), ('oral_care', 'Oral Care / Dental Hygiene'), ('continence', 'Continence Care'), ('pressure_care', 'Pressure Area Care'), ('repositioning', 'Repositioning / Turning'), ('nutrition', 'Nutrition & Meal Record'), ('hydration', 'Fluid / Hydration Record'), ('weight', 'Weight Check'), ('mobility', 'Mobility & Moving'), ('activity', 'Activity & Engagement'), ('physiotherapy', 'Physiotherapy / Exercise'), ('emotional', 'Emotional Wellbeing'), ('behaviour', 'Behaviour / Incident Note'), ('sleep', 'Sleep Record'), ('social', 'Social Interaction'), ('clinical', 'Clinical / Nursing Note'), ('wound', 'Wound Care'), ('catheter', 'Catheter Care'), ('stoma', 'Stoma Care'), ('medication_note', 'Medication Note (Non-Admin)'), ('family_contact', 'Family / Next of Kin Contact'), ('gp_contact', 'GP / Healthcare Professional Contact'), ('safeguarding', 'Safeguarding Note'), ('handover', 'Shift Handover Note'), ('general', 'General Note')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='carenote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carenote',
            name='note_text',
            field=models.TextField(blank=True),
        ),
    ]
