# Generated by Django 4.2.30 on 2026-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_notes', '0002_remove_carenote_updated_at_carenote_appetite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenote',
            name='category',
            field=models.CharField(choices=[('', '-Select Category-'), ('general', 'General Note'), ('observation_60', '60 Min (Hourly) Observation'), ('observation_30', '30 Min Observation'), ('observation_15', '15 Min Observation'), ('observation_eod', 'End of Shift / Timeline Review'), ('personal_care', 'Personal Care'), ('oral_care', 'Oral Care / Dental Hygiene'), ('continence', 'Continence Care'), ('pressure_care', 'Pressure Area Care'), ('repositioning', 'Repositioning / Turning'), ('nutrition', 'Nutrition & Meal Record'), ('hydration', 'Fluid / Hydration Record'), ('weight', 'Weight Check'), ('mobility', 'Mobility & Moving'), ('activity', 'Activity & Engagement'), ('physiotherapy', 'Physiotherapy / Exercise'), ('emotional', 'Emotional Wellbeing'), ('behaviour', 'Behaviour / Incident Note'), ('sleep', 'Sleep Record'), ('social', 'Social Interaction'), ('clinical', 'Clinical / Nursing Note'), ('wound', 'Wound Care'), ('catheter', 'Catheter Care'), ('stoma', 'Stoma Care'), ('medication_note', 'Medication Note (Non-Admin)'), ('family_contact', 'Family / Next of Kin Contact'), ('gp_contact', 'GP / Healthcare Professional Contact'), ('safeguarding', 'Safeguarding Note'), ('handover', 'Shift Handover Note')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carenote',
            name='priority',
            field=models.CharField(choices=[('', '-Select Priority-'), ('routine', 'Routine'), ('important', 'Important'), ('urgent', 'Urgent')], max_length=10),
        ),
    ]
