# Generated by Django 4.2.30 on 2026-08-27 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_notes', '0004_voicecarenotedraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareNoteSummaryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_note_count', models.PositiveIntegerField()),
                ('summary_text', models.TextField()),
                ('rouge1', models.FloatField(blank=True, null=True)),
                ('rouge2', models.FloatField(blank=True, null=True)),
                ('rougeL', models.FloatField(blank=True, null=True)),
                ('bleu', models.FloatField(blank=True, null=True)),
                ('bertscore_precision', models.FloatField(blank=True, null=True)),
                ('bertscore_recall', models.FloatField(blank=True, null=True)),
                ('bertscore_f1', models.FloatField(blank=True, null=True)),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
