# Generated by Django 4.2.30 on 2026-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallalert',
            name='label',
            field=models.CharField(choices=[('fallen', 'Fallen/Falling')], max_length=20),
        ),
    ]
